### ISSUE TITLE
Error in HA log

### ISSUE THREAD

**Issue by Calimerorulez** [rstrouse/ESPSomfy-RTS-HA#42]
Hi,

Just updated to HA 2024.3, and I was checking the logs. I saw this error a couple of times:

```

Logger: homeassistant.helpers.entity
Bron: helpers/entity.py:945
First occurred: 20:36:44 (2 gebeurtenissen)
Laatst gelogd: 20:36:44

Update for update.espsomfy_rts_851af8 fails
Update for update.espsomfy_rts_a62c1c fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 945, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1262, in async_device_update
    await self.async_update()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 535, in async_update
    await self.coordinator.async_request_refresh()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 268, in async_request_refresh
    await self._debounced_refresh.async_call()
  File "/usr/src/homeassistant/homeassistant/helpers/debounce.py", line 112, in async_call
    await task
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 294, in async_refresh
    await self._async_refresh(log_failures=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 384, in _async_refresh
    raise err
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 318, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 273, in _async_update_data
    raise NotImplementedError("Update method not implemented")
NotImplementedError: Update method not implemented
```

**Comment by rstrouse** [comment]
I have been looking at this cannot seem to duplicate it.  However, I have not updated my dev system to 2024.3 yet.  This message is coming from the update entity for the firmware.

**Comment by rstrouse** [comment]
@Calimerorulez any more details on this.  I cannot seem to replicate it.

**Comment by Calimerorulez** [comment]
It just reappeared after restarting HA:



Logger: homeassistant.helpers.entity
Bron: helpers/entity.py:951
Eerst voorgekomen: 07:05:49 (2 gebeurtenissen)
Laatst gelogd: 07:05:49

Update for update.espsomfy_rts_851af8 fails
Update for update.espsomfy_rts_a62c1c fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 951, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1268, in async_device_update
    await self.async_update()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 532, in async_update
    await self.coordinator.async_request_refresh()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 265, in async_request_refresh
    await self._debounced_refresh.async_call()
  File "/usr/src/homeassistant/homeassistant/helpers/debounce.py", line 117, in async_call
    await task
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 291, in async_refresh
    await self._async_refresh(log_failures=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 381, in _async_refresh
    raise err
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 315, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 270, in _async_update_data
    raise NotImplementedError("Update method not implemented")
NotImplementedError: Update method not implemented
