### ISSUE TITLE
HA intergration don't boot

### ISSUE THREAD

**Issue by Arighaii** [rstrouse/ESPSomfy-RTS-HA#59]
Hello,

I have an issue with the integration booting, when i want to add the esp, i get a blank popup after validating the IP and nothing happen. When checking in the logs i see that the component didn't boot properly but i can find why.
Based on my past issue with other custom_component, i've checked that HA have all access on the files and folders, rebooted 2 times the HA server but i can't make it work. Any kind of help would be appreciated :)
Hypothesis would be an HA version issue, just want confirmation if it's the case or not.

Thanks for your time

HA version : 2023.7.3 (Synocommunity)

Log : 
Logger: homeassistant
Source: custom_components/espsomfy_rts/config_flow.py:161
Integration: espsomfy_rts ([documentation](https://github.com/rstrouse/ESPSomfy-RTS/wiki/Configuring-the-Software))
First occurred: 7 mai 2024 à 22:36:48 (1 occurrences)
Last logged: 7 mai 2024 à 22:36:48
Error doing job: Task exception was never retrieved

Traceback (most recent call last):
  File "/volume2/@appstore/homeassistant/env/lib/python3.11/site-packages/homeassistant/helpers/discovery_flow.py", line 95, in _async_start
    await gather_with_concurrency(
  File "/volume2/@appstore/homeassistant/env/lib/python3.11/site-packages/homeassistant/util/async_.py", line 185, in gather_with_concurrency
    return await gather(
           ^^^^^^^^^^^^^
  File "/volume2/@appstore/homeassistant/env/lib/python3.11/site-packages/homeassistant/util/async_.py", line 183, in sem_task
    return await task
           ^^^^^^^^^^
  File "/volume2/@appstore/homeassistant/env/lib/python3.11/site-packages/homeassistant/config_entries.py", line 856, in async_init
    flow, result = await task
                   ^^^^^^^^^^
  File "/volume2/@appstore/homeassistant/env/lib/python3.11/site-packages/homeassistant/config_entries.py", line 884, in _async_init
    result = await self._async_handle_step(flow, flow.init_step, data)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/volume2/@appstore/homeassistant/env/lib/python3.11/site-packages/homeassistant/data_entry_flow.py", line 393, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/volume2/@appdata/homeassistant/config/custom_components/espsomfy_rts/config_flow.py", line 143, in async_step_zeroconf
    return await self.async_step_zeroconf_confirm()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/volume2/@appdata/homeassistant/config/custom_components/espsomfy_rts/config_flow.py", line 161, in async_step_zeroconf_confirm
    "model": self.zero_conf.model,
             ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ZeroconfServiceInfo' object has no attribute 'model'

**Comment by rstrouse** [comment]
Yes this is likely a version difference but I should be more defensive in checking the attributes before accessing them.  I will change the code so that it does a more graceful get of the model property.  I have a couple of other items in the plugin that I am finishing up but will post a new version soon.

**Comment by Arighaii** [comment]
Works perfectly with the lastest release, thanks for your hardwork
