### ISSUE TITLE
Error when using 'ESPSomfy RTS: Set Position' service

### ISSUE THREAD

**Issue by ticarki** [rstrouse/ESPSomfy-RTS-HA#6]
Great Integration, exactly what I needed, thanks! I updated the integration yesterday and wanted to use the set position state. When I select a shade and set a percentage (e.g., 20) I get the following error:

```
extra keys not allowed @ data['position']. Got None
```

The open and close services work perfectly, any idea?

**Comment by rstrouse** [comment]
Uggh,  I set the wrong attribute to the position value.  Update to v1.0.11 and this should be fixed for the services.

**Comment by ticarki** [comment]
Thanks for the quick fix. I got it running after casting the string kwargs[ATTR_POSITION] variable to an integer in cover.py:217. Thanks!

```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 26, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 647, in handle_execute_script
    await script_obj.async_run(msg.get("variables"), context=context)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1533, in async_run
    await asyncio.shield(run.async_run())
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 410, in async_run
    await self._async_step(log_exceptions=False)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 454, in _async_step
    self._handle_exception(
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 477, in _handle_exception
    raise exception
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 452, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 685, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1820, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1857, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 809, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 798, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 977, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 838, in _handle_entity_call
    await result
  File "/config/custom_components/espsomfy_rts/cover.py", line 217, in async_set_cover_position
    self._shade_id, 100 - kwargs[ATTR_POSITION]
TypeError: unsupported operand type(s) for -: 'int' and 'str'
```

**Comment by rstrouse** [comment]
v1.0.12 has been published.  I added coercion to the service schema so all input values for position and tilt_position are coerced into integer values.  This would have worked fine if your service call was using ints not strings but now it will perform that conversion before making the call.

**Comment by ticarki** [comment]
Great, thank you, with the new version, I don't get any errors.
