### ISSUE TITLE
upgrade to v2.4.5 fails with error "failed to call service update/install. tuple index out of range"

### ISSUE THREAD

**Issue by HansVanEylen** [rstrouse/ESPSomfy-RTS-HA#73]
Home Assistant indicated there was an update to the firmware. When I clicked to install, it failed immediately with the message : "failed to call service update/install. tuple index out of range".

This is logged : 

Logger: homeassistant.components.websocket_api.http.connection
Source: components/websocket_api/commands.py:241
integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 08:10:03 (3 occurrences)
Last logged: 13:19:24

[139745751934736] Unexpected exception
[139745751929120] Unexpected exception
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 241, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2741, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2784, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 977, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1049, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/update/__init__.py", line 157, in async_install
    await entity.async_install_with_progress(version, backup)
  File "/usr/src/homeassistant/homeassistant/components/update/__init__.py", line 461, in async_install_with_progress
    await self.async_install(version, backup)
  File "/config/custom_components/espsomfy_rts/update.py", line 118, in async_install
    success = await self._controller.create_backup()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/espsomfy_rts/controller.py", line 285, in create_backup
    return await self.api.create_backup()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/espsomfy_rts/controller.py", line 601, in create_backup
    with open(file=fpath, mode="wb+") as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 123, in protected_loop_func
    raise_for_blocking_call(
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 42, in raise_for_blocking_call
    if check_allowed is not None and check_allowed(mapped_args):
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/block_async_io.py", line 28, in _check_file_allowed
    path = args[0] if type(args[0]) is str else str(args[0])  # noqa: E721
                           ~~~~^^^
IndexError: tuple index out of range


which seems to be almost the same as https://github.com/rstrouse/ESPSomfy-RTS/issues/401.

**Comment by Jezza34000** [comment]
Update to the last version of the component and this will be gone :-)

**Comment by HansVanEylen** [comment]
I actually thought about that but when I checked there was no new version (yet). Only some time after I upgraded ESPSompfy-RTS on its own, the component upgrade appeared.

**Comment by rstrouse** [comment]
I am going to close this out as it was due to a breaking change in HA core and a fix has been applied.
